=== AnonymerNiklasistanonym/BanBotsTwitch/src/credentials.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Credentials",
    "definitions": {
        "Credentials": {
            "type": "object",
            "properties": {
                "$schema": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirectPort": {
                    "type": "number"
                }
            },
            "required": [
                "clientId",
                "clientSecret",
                "scopes",
                "redirectPort"
            ],
            "additionalProperties": false
        }
    }
}

=== AnonymerNiklasistanonym/BanBotsTwitch/credentials_example.json
{
    "clientId": "GET THIS FROM https://dev.twitch.tv/console/apps",
    "clientSecret": "GET THIS FROM https://dev.twitch.tv/console/apps",
    "scopes": [
        "chat:read",
        "chat:edit",
        "moderator:read:followers",
        "moderator:manage:banned_users"
    ],
    "redirectPort": 7270
}
